trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: |
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: 'New-Item -Path ''C:\Sample-demo'' -ItemType Directory'
#   displayName: 'Run a one-line script'


- task: PowerShell@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    azurePowerShellVersion: 'LatestVersion'
    machineType: 'Windows'
    targetMachines: '20.81.154.101'
    targetType: 'inline'
    script: 'Invoke-AzVMRunCommand -ResourceGroupName ''demoVM2_group'' -Name ''demoVM2'' -CommandId ''RunPowerShellScript'' -ScriptPath ''C:\agent\run.cmd'' -Parameter @{"arg1" = "var1";"arg2" = "var2"}'