trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- script: |
# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: 'New-Item -Path ''C:\Sample-demo'' -ItemType Directory'
#   displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    azurePowerShellVersion: 'LatestVersion'
    machineType: 'Windows'
    targetMachines: '20.81.154.101'
    targetType: 'inline'
    script: 'C:\agent\run.cmd'